2024-06-23 23:00:30.531688: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-23 23:00:30.549197: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-23 23:00:30.709184: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-23 23:00:30.709734: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-23 23:00:32.312417: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "test.py", line 166, in <module>
    main(args.student_id)
  File "test.py", line 129, in main
    game_results = play_games(student_id, student_ai, f'baseline{i}', baseline_ai)
  File "test.py", line 88, in play_games
    config.register_player(name=student_id, algorithm=student_ai())
  File "/home/ubitus03/fai_final_project/./b11505050/agent.py", line 203, in setup_ai
    return trainedPlayer()
  File "/home/ubitus03/fai_final_project/./b11505050/agent.py", line 26, in __init__
    self.model = self.load_model('./src/poker_model.h5')
  File "/home/ubitus03/fai_final_project/./b11505050/agent.py", line 37, in load_model
    return tf.keras.models.load_model(model_path)
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubitus03/miniconda3/envs/poker/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at ./src/poker_model.h5
